import pandas as pd

_EM_EDGE_LIST = [
    {
        'node_1': 1,
        'node_2': 2,
        'weight': 18,
        'color': 'black',
        },
    {
        'node_1': 1,
        'node_2': 12,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 2,
        'node_2': 1,
        'weight': 18,
        'color': 'black',
        },
    {
        'node_1': 2,
        'node_2': 3,
        'weight': 22,
        'color': 'black',
        },
    {
        'node_1': 2,
        'node_2': 13,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 3,
        'node_2': 2,
        'weight': 22,
        'color': 'black',
        },
    {
        'node_1': 3,
        'node_2': 4,
        'weight': 20,
        'color': 'black',
        },
    {
        'node_1': 3,
        'node_2': 14,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 4,
        'node_2': 3,
        'weight': 20,
        'color': 'black',
        },
    {
        'node_1': 4,
        'node_2': 5,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 4,
        'node_2': 19,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 5,
        'node_2': 4,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 5,
        'node_2': 6,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 5,
        'node_2': 20,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 6,
        'node_2': 5,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 6,
        'node_2': 7,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 6,
        'node_2': 21,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 7,
        'node_2': 6,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 7,
        'node_2': 8,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 7,
        'node_2': 22,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 8,
        'node_2': 7,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 8,
        'node_2': 9,
        'weight': 16,
        'color': 'black',
        },
    {
        'node_1': 8,
        'node_2': 23,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 9,
        'node_2': 8,
        'weight': 16,
        'color': 'black',
        },
    {
        'node_1': 9,
        'node_2': 10,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 9,
        'node_2': 24,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 10,
        'node_2': 9,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 10,
        'node_2': 11,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 10,
        'node_2': 26,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 11,
        'node_2': 10,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 11,
        'node_2': 27,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 12,
        'node_2': 1,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 12,
        'node_2': 13,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 12,
        'node_2': 15,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 13,
        'node_2': 2,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 13,
        'node_2': 12,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 13,
        'node_2': 14,
        'weight': 21,
        'color': 'black',
        },
    {
        'node_1': 13,
        'node_2': 16,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 14,
        'node_2': 3,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 14,
        'node_2': 13,
        'weight': 21,
        'color': 'black',
        },
    {
        'node_1': 14,
        'node_2': 18,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 15,
        'node_2': 12,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 15,
        'node_2': 16,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 15,
        'node_2': 28,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 16,
        'node_2': 13,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 16,
        'node_2': 15,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 16,
        'node_2': 17,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 16,
        'node_2': 29,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 17,
        'node_2': 16,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 17,
        'node_2': 18,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 17,
        'node_2': 30,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 18,
        'node_2': 14,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 18,
        'node_2': 17,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 18,
        'node_2': 19,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 18,
        'node_2': 31,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 19,
        'node_2': 4,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 19,
        'node_2': 18,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 19,
        'node_2': 20,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 19,
        'node_2': 32,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 20,
        'node_2': 5,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 20,
        'node_2': 19,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 20,
        'node_2': 21,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 20,
        'node_2': 33,
        'weight': 12,
        'color': 'black',
        },
    {
        'node_1': 21,
        'node_2': 6,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 21,
        'node_2': 20,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 21,
        'node_2': 22,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 21,
        'node_2': 34,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 22,
        'node_2': 7,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 22,
        'node_2': 21,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 22,
        'node_2': 23,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 22,
        'node_2': 35,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 23,
        'node_2': 8,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 23,
        'node_2': 22,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 23,
        'node_2': 24,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 23,
        'node_2': 36,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 24,
        'node_2': 9,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 24,
        'node_2': 23,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 24,
        'node_2': 25,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 24,
        'node_2': 37,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 25,
        'node_2': 24,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 25,
        'node_2': 26,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 25,
        'node_2': 38,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 26,
        'node_2': 10,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 26,
        'node_2': 25,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 26,
        'node_2': 27,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 26,
        'node_2': 39,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 27,
        'node_2': 11,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 27,
        'node_2': 26,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 27,
        'node_2': 40,
        'weight': 12,
        'color': 'black',
        },
    {
        'node_1': 28,
        'node_2': 15,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 28,
        'node_2': 29,
        'weight': 16,
        'color': 'black',
        },
    {
        'node_1': 28,
        'node_2': 41,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 29,
        'node_2': 16,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 29,
        'node_2': 28,
        'weight': 16,
        'color': 'black',
        },
    {
        'node_1': 29,
        'node_2': 30,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 29,
        'node_2': 42,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 30,
        'node_2': 17,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 30,
        'node_2': 29,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 30,
        'node_2': 31,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 31,
        'node_2': 18,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 31,
        'node_2': 30,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 31,
        'node_2': 32,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 31,
        'node_2': 43,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 32,
        'node_2': 19,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 32,
        'node_2': 31,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 32,
        'node_2': 33,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 32,
        'node_2': 44,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 33,
        'node_2': 20,
        'weight': 12,
        'color': 'black',
        },
    {
        'node_1': 33,
        'node_2': 32,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 33,
        'node_2': 34,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 33,
        'node_2': 45,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 34,
        'node_2': 21,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 34,
        'node_2': 33,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 34,
        'node_2': 35,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 34,
        'node_2': 46,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 35,
        'node_2': 22,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 35,
        'node_2': 34,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 35,
        'node_2': 36,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 35,
        'node_2': 47,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 36,
        'node_2': 23,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 36,
        'node_2': 35,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 36,
        'node_2': 37,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 36,
        'node_2': 48,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 37,
        'node_2': 24,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 37,
        'node_2': 36,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 37,
        'node_2': 38,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 37,
        'node_2': 49,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 38,
        'node_2': 25,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 38,
        'node_2': 37,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 38,
        'node_2': 39,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 38,
        'node_2': 50,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 39,
        'node_2': 26,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 39,
        'node_2': 38,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 39,
        'node_2': 40,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 39,
        'node_2': 51,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 40,
        'node_2': 27,
        'weight': 12,
        'color': 'black',
        },
    {
        'node_1': 40,
        'node_2': 39,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 40,
        'node_2': 52,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 41,
        'node_2': 28,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 41,
        'node_2': 42,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 41,
        'node_2': 53,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 42,
        'node_2': 29,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 42,
        'node_2': 41,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 42,
        'node_2': 43,
        'weight': 18,
        'color': 'black',
        },
    {
        'node_1': 42,
        'node_2': 54,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 43,
        'node_2': 31,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 43,
        'node_2': 42,
        'weight': 18,
        'color': 'black',
        },
    {
        'node_1': 43,
        'node_2': 44,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 43,
        'node_2': 56,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 44,
        'node_2': 32,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 44,
        'node_2': 43,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 44,
        'node_2': 45,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 44,
        'node_2': 57,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 45,
        'node_2': 33,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 45,
        'node_2': 44,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 45,
        'node_2': 46,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 45,
        'node_2': 58,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 46,
        'node_2': 34,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 46,
        'node_2': 45,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 46,
        'node_2': 47,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 46,
        'node_2': 59,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 47,
        'node_2': 35,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 47,
        'node_2': 46,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 47,
        'node_2': 48,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 47,
        'node_2': 60,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 48,
        'node_2': 36,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 48,
        'node_2': 47,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 48,
        'node_2': 61,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 49,
        'node_2': 37,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 49,
        'node_2': 50,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 49,
        'node_2': 62,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 50,
        'node_2': 38,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 50,
        'node_2': 49,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 50,
        'node_2': 51,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 50,
        'node_2': 63,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 51,
        'node_2': 39,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 51,
        'node_2': 50,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 51,
        'node_2': 52,
        'weight': 15,
        'color': 'black',
        },
    {
        'node_1': 51,
        'node_2': 64,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 52,
        'node_2': 40,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 52,
        'node_2': 51,
        'weight': 15,
        'color': 'black',
        },
    {
        'node_1': 52,
        'node_2': 65,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 53,
        'node_2': 41,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 53,
        'node_2': 54,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 53,
        'node_2': 66,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 54,
        'node_2': 42,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 54,
        'node_2': 53,
        'weight': 13,
        'color': 'black',
        },
    {
        'node_1': 54,
        'node_2': 55,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 54,
        'node_2': 67,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 55,
        'node_2': 54,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 55,
        'node_2': 56,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 55,
        'node_2': 68,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 56,
        'node_2': 43,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 56,
        'node_2': 55,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 56,
        'node_2': 57,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 56,
        'node_2': 69,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 57,
        'node_2': 44,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 57,
        'node_2': 56,
        'weight': 8,
        'color': 'black',
        },
    {
        'node_1': 57,
        'node_2': 58,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 58,
        'node_2': 45,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 58,
        'node_2': 57,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 58,
        'node_2': 59,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 58,
        'node_2': 70,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 59,
        'node_2': 46,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 59,
        'node_2': 58,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 59,
        'node_2': 60,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 59,
        'node_2': 71,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 60,
        'node_2': 47,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 60,
        'node_2': 59,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 60,
        'node_2': 61,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 60,
        'node_2': 72,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 61,
        'node_2': 48,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 61,
        'node_2': 60,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 61,
        'node_2': 62,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 62,
        'node_2': 49,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 62,
        'node_2': 61,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 62,
        'node_2': 63,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 62,
        'node_2': 73,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 63,
        'node_2': 50,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 63,
        'node_2': 62,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 63,
        'node_2': 64,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 63,
        'node_2': 74,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 64,
        'node_2': 51,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 64,
        'node_2': 63,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 64,
        'node_2': 65,
        'weight': 17,
        'color': 'black',
        },
    {
        'node_1': 64,
        'node_2': 75,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 65,
        'node_2': 52,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 65,
        'node_2': 64,
        'weight': 17,
        'color': 'black',
        },
    {
        'node_1': 65,
        'node_2': 76,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 66,
        'node_2': 53,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 66,
        'node_2': 67,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 67,
        'node_2': 54,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 67,
        'node_2': 66,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 67,
        'node_2': 68,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 68,
        'node_2': 55,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 68,
        'node_2': 67,
        'weight': 10,
        'color': 'black',
        },
    {
        'node_1': 68,
        'node_2': 69,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 69,
        'node_2': 56,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 69,
        'node_2': 68,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 69,
        'node_2': 70,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 70,
        'node_2': 58,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 70,
        'node_2': 69,
        'weight': 11,
        'color': 'black',
        },
    {
        'node_1': 70,
        'node_2': 71,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 71,
        'node_2': 59,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 71,
        'node_2': 70,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 71,
        'node_2': 72,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 72,
        'node_2': 60,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 72,
        'node_2': 71,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 72,
        'node_2': 73,
        'weight': 18,
        'color': 'black',
        },
    {
        'node_1': 72,
        'node_2': 77,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 73,
        'node_2': 62,
        'weight': 1,
        'color': 'black',
        },
    {
        'node_1': 73,
        'node_2': 72,
        'weight': 18,
        'color': 'black',
        },
    {
        'node_1': 73,
        'node_2': 74,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 73,
        'node_2': 78,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 74,
        'node_2': 63,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 74,
        'node_2': 73,
        'weight': 9,
        'color': 'black',
        },
    {
        'node_1': 74,
        'node_2': 75,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 75,
        'node_2': 64,
        'weight': 3,
        'color': 'black',
        },
    {
        'node_1': 75,
        'node_2': 74,
        'weight': 7,
        'color': 'black',
        },
    {
        'node_1': 75,
        'node_2': 76,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 75,
        'node_2': 79,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 76,
        'node_2': 65,
        'weight': 2,
        'color': 'black',
        },
    {
        'node_1': 76,
        'node_2': 75,
        'weight': 14,
        'color': 'black',
        },
    {
        'node_1': 76,
        'node_2': 80,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 77,
        'node_2': 72,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 77,
        'node_2': 78,
        'weight': 17,
        'color': 'black',
        },
    {
        'node_1': 78,
        'node_2': 73,
        'weight': 4,
        'color': 'black',
        },
    {
        'node_1': 78,
        'node_2': 77,
        'weight': 17,
        'color': 'black',
        },
    {
        'node_1': 79,
        'node_2': 75,
        'weight': 6,
        'color': 'black',
        },
    {
        'node_1': 79,
        'node_2': 80,
        'weight': 12,
        'color': 'black',
        },
    {
        'node_1': 80,
        'node_2': 76,
        'weight': 5,
        'color': 'black',
        },
    {
        'node_1': 80,
        'node_2': 79,
        'weight': 12,
        'color': 'black',
    },
]

EM_EDGE_LIST = pd.DataFrame.from_dict(_EM_EDGE_LIST)